### ISSUE TITLE
firrtl parsing error on string literal with escaped double quotes

### ISSUE THREAD

**Issue by chick** [ucb-bar/chisel3#111]
Pushed a branch to chisel3 named assert_message_causes_firrtl_quote_parsing_error (nice name)

Add new AssertQuoteProblem test that shows how adding a message param to Chisel.assert.apply causes a firrtl parsing error apparently because the string has escaped double quotes in it.
Error is
```
 [0.053] Done elaborating.
line 27:164 token recognition error at: '\'
line 27:165 extraneous input '")\n"' expecting {'circuit', 'module', 'extmodule', 'input', 'output', 'UInt', 'SInt', 'Clock', '[', 'wire', 'reg', 'with', 'reset', ')', 'mem', 'data-type', 'depth', 'read-latency', 'write-latency', 'read-under-write', 'reader', 'writer', 'readwriter', 'inst', 'node', 'is', 'invalid', 'when', 'else', 'skip', 'infer', 'read', 'write', 'rdwr', 'old', 'new', 'undefined', 'UBits', 'SBits', '.', 'mux(', 'validif(', 'stop', 'printf', 'mux', 'validif', 'add(', 'sub(', 'mul(', 'div(', 'rem(', 'lt(', 'leq(', 'gt(', 'geq(', 'eq(', 'neq(', 'pad(', 'asUInt(', 'asSInt(', 'asClock(', 'shl(', 'shr(', 'dshl(', 'dshr(', 'cvt(', 'neg(', 'not(', 'and(', 'or(', 'xor(', 'andr(', 'orr(', 'xorr(', 'cat(', 'bits(', 'head(', 'tail(', Id}
Exception in thread "main" firrtl.ParserException: 1 syntax error(s) detected
	at firrtl.Parser$.parse(Parser.scala:64)
	at firrtl.Driver$.compile(Driver.scala:52)
	at firrtl.Driver$.main(Driver.scala:95)
	at firrtl.Driver.main(Driver.scala)
```
Attached is the *.fir file with problematic string literal at line 27
[*fir.txt](https://github.com/ucb-bar/chisel3/files/147726/fir.txt)

Not really a show stopper, but caused some problems in new testers

**Comment by ucbjrl** [comment]
I believe this was fixed with firrtl d1d95d464d7ce68e02e0d5b55886a4038f088a76. In any case, recent versions of this test pass.
