### ISSUE TITLE
Bulk Connect to Black Box doesn't work

### ISSUE THREAD

**Issue by mwachs5** [ucb-bar/chisel3#279]
If you define a bundle for the IO of a black box, you can't bulk connect to it. I think the problem is the fact that BlackBoxes bundle names don't have 'io' in them, so the name lookup doesn't work.

```
class MySimpleIO extends Bundle {
  val a = Bool(INPUT)
  val b = Bool (OUTPUT)
}

class MySimpleModule extends Module {

  val io = new MySimpleIO

  val my_bb_inst = Module (new MySimpleBlackBox)
  val my_non_bb_inst = Module (new MySimpleNonBlackBox)

  // uncommenting this line will cause an exception during Emitter stage (see below):
  // io := my_bb_inst.io

  // But this way works fine
  io := my_non_bb_inst.io
}

class MySimpleBlackBox extends BlackBox {
  val io = new MySimpleIO
}

class MySimpleNonBlackBox extends Module {
  val io = new MySimpleIO
  io.b := io.a
}

```

Here's the exception:

```
[info] [10.569] Done elaborating.
[error] (run-main-0) java.util.NoSuchElementException: None.get
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:347)
	at scala.None$.get(Option.scala:345)
	at chisel3.internal.HasId$class.getRef(Builder.scala:108)
	at chisel3.core.Data.getRef(Data.scala:30)
	at chisel3.internal.firrtl.Node.fullName(IR.scala:53)
	at chisel3.internal.firrtl.Emitter.chisel3$internal$firrtl$Emitter$$emit(Emitter.scala:26)

```

**Comment by mwachs5** [comment]
Ah I see this is the same as #249.
