### ISSUE TITLE
chisel3.util.pipe is broken

### ISSUE THREAD

**Issue by SpaceCowboyMax** [ucb-bar/chisel3#615]
Hello!
After last release, simple instantiation of pipe module gives error
example
```Scala
class Sample extends Module {
  val io = IO(new Bundle {
    val a = Input(Bool())
    val b = Input(UInt(32.W))
  })
  val pipe = Module(new Pipe(UInt(32.W), 32))
  pipe.io.enq.valid <> io.a
  pipe.io.enq.bits <> io.b
}
object Sample extends App {
  Driver.execute(Array("-td", "./"), () => new Sample)
}
```
dat code gives an error
Exception in thread "main" chisel3.internal.ChiselException: Connection between left (chisel3.core.Bool@cc) and source (chisel3.core.Bool@c2) failed @: Locally unclear whether Left or Right (both internal)
	at chisel3.internal.throwException$.apply(Error.scala:13)
	at chisel3.core.Data.bulkConnect(Data.scala:222)
	at chisel3.core.Data.$less$greater(Data.scala:273)
	at chisel3.util.Pipe$.apply(Valid.scala:41)
...
etc

**Comment by ucbjrl** [comment]
Thanks for reporting this.

This is due to pr #592 (the removal of the `import chisel3.core.ExplicitCompileOptions.NotStrict` on internal library implementations), coupled with the old `Pipe` implementation.
